/*

Maria 1.1.0
Copyright (c) 2013, Peter Michaux
All rights reserved.
Licensed under the Simplified BSD License.
http://peter.michaux.ca/downloads/maria/1.1.0/LICENSE
*/
var maria=function(){var k,t,u,v;k=function(){};k.superConstructor=Object;(function(){function d(d,b){return Object.prototype.hasOwnProperty.call(d,b)}var b=function(){function d(){}return function(b){d.prototype=b;b=new d;d.prototype=null;return b}}();k.prototype.addEventListener=function(b,e){d(this,"_evento_listeners")||(this._evento_listeners={});d(this._evento_listeners,b)||(this._evento_listeners[b]=[]);for(var a=this._evento_listeners[b],f=0,l=a.length;f<l;f++)if(a[f]===e)return;a.push(e)};
k.prototype.removeEventListener=function(b,a){if(d(this,"_evento_listeners")&&d(this._evento_listeners,b))for(var g=this._evento_listeners[b],f=0,l=g.length;f<l;f++)if(g[f]===a){g.splice(f,1);break}};k.prototype.addParentEventTarget=function(b){if("function"!==typeof b.dispatchEvent)throw new TypeError("evento.EventTarget.prototype.addParentEventTarget: Parents must have dispatchEvent method.");d(this,"_evento_parents")||(this._evento_parents=[]);for(var a=this._evento_parents,g=0,f=a.length;g<f;g++)if(a[g]===
b)return;a.push(b)};k.prototype.removeParentEventTarget=function(b){if(d(this,"_evento_parents"))for(var a=this._evento_parents,g=0,f=a.length;g<f;g++)if(a[g]===b){a.splice(g,1);break}};k.prototype.dispatchEvent=function(c){c=b(c);"target"in c||(c.target=this);c.currentTarget=this;c._propagationStopped="bubbles"in c?!c.bubbles:!1;c.stopPropagation=function(){c._propagationStopped=!0};if(d(this,"_evento_listeners")&&d(this._evento_listeners,c.type))for(var a=this._evento_listeners[c.type].slice(0),
g=0,f=a.length;g<f;g++){var l=a[g];"function"===typeof l?l.call(this,c):l.handleEvent(c)}if(d(this,"_evento_parents")&&!c._propagationStopped)for(a=this._evento_parents.slice(0),g=0,f=a.length;g<f;g++)a[g].dispatchEvent(c)};k.call(k.prototype);k.mixin=function(b){var a=k.prototype,g;for(g in a)d(a,g)&&"function"===typeof a[g]&&(b[g]=a[g]);k.call(b)}})();(function(){function d(b,d,a,c){var p={element:b,type:d,listener:a};3<arguments.length&&(p.auxArg=c);if("function"===typeof a){var h=3<arguments.length?
c:b;p.wrappedHandler=function(b){a.call(h,b)}}else if("function"===typeof c)p.wrappedHandler=function(b){c.call(a,b)};else{var x=3<arguments.length?c:"handleEvent";p.wrappedHandler=function(b){a[x](b)}}return p}function b(b,d){for(var a=0,c=b.length;a<c;a++)if(b[a].element===d.element&&b[a].type===d.type&&b[a].listener===d.listener&&(!b[a].hasOwnProperty("auxArg")&&!d.hasOwnProperty("auxArg")||b[a].hasOwnProperty("auxArg")&&d.hasOwnProperty("auxArg")&&b[a].auxArg===d.auxArg))return a;return-1}t=function(a,
c,f,l){var p=d.apply(null,arguments);if(f._evento_bundles){if(0<=b(f._evento_bundles,p))return}else f._evento_bundles=[];if("function"===typeof p.element.addEventListener)p.element.addEventListener(p.type,p.wrappedHandler,!1);else if("object"===typeof p.element.attachEvent&&null!==p.element.attachEvent)p.element.attachEvent("on"+p.type,p.wrappedHandler);else throw Error("evento.on: Supported EventTarget interface not found.");f._evento_bundles.push(p)};var a=u=function(a,c,f,l){if(f._evento_bundles){var p=
b(f._evento_bundles,d.apply(null,arguments));if(0<=p){var h=f._evento_bundles[p];if("function"===typeof h.element.removeEventListener)h.element.removeEventListener(h.type,h.wrappedHandler,!1);else if("object"===typeof h.element.detachEvent&&null!==h.element.detachEvent)h.element.detachEvent("on"+h.type,h.wrappedHandler);else throw Error("evento.off: Supported EventTarget interface not found.");f._evento_bundles.splice(p,1)}}};v=function(b){if(b._evento_bundles){b=b._evento_bundles.slice(0);for(var d=
0,f=b.length;d<f;d++){var l=b[d];l.hasOwnProperty("auxArg")?a(l.element,l.type,l.listener,l.auxArg):a(l.element,l.type,l.listener)}}}})();var q,m;q=function(){this.nextSibling=this.previousSibling=this.parentNode=null};q.superConstructor=Object;q.prototype.destroy=function(){this.nextSibling=this.previousSibling=this.parentNode=null};q.call(q.prototype);q.mixin=function(d){d.destroy=q.prototype.destroy;q.call(d)};m=function(){q.call(this);this.childNodes=[];this.lastChild=this.firstChild=null};m.superConstructor=
q;m.prototype=function(){function d(){}d.prototype=q.prototype;return new d}();m.prototype.constructor=m;m.prototype.destroy=function(){for(var d=this.childNodes.slice(0),b=0,a=d.length;b<a;b++)d[b].destroy();q.prototype.destroy.call(this);this.lastChild=this.firstChild=this.childNodes=null};m.prototype.hasChildNodes=function(){return 0<this.childNodes.length};m.prototype.insertBefore=function(d,b){if(2>arguments.length)throw Error("hijos.Node.prototype.insertBefore: not enough arguments.");void 0===
b&&(b=null);if(!(d===b||b&&b.previousSibling===d||null===b&&this.lastChild===d)){for(var a=this;a;){if(a===d)throw Error("hijos.Node.prototype.insertBefore: Node cannot be inserted at the specified point in the hierarchy.");a=a.parentNode}(a=d.parentNode)&&a.removeChild(d);var a=this.childNodes,e;if(null===b)e=a.length;else{for(var g=0,f=a.length;g<f;g++)if(a[g]===b){e=g;break}if("number"!==typeof e)throw Error("hijos.Node.prototype.insertBefore: Node was not found.");}a.splice(e,0,d);this.firstChild=
a[0];this.lastChild=a[a.length-1];d.parentNode=this;if(g=d.previousSibling=a[e-1]||null)g.nextSibling=d;if(e=d.nextSibling=a[e+1]||null)e.previousSibling=d}};m.prototype.appendChild=function(a){if(1>arguments.length)throw Error("hijos.Node.prototype.appendChild: not enough arguments.");this.insertBefore(a,null)};m.prototype.replaceChild=function(a,b){if(2>arguments.length)throw Error("hijos.Node.prototype.replaceChild: not enough arguments.");if(!b)throw Error("hijos.Node.prototype.replaceChild: oldChild must not be falsy.");
a!==b&&(this.insertBefore(a,b),this.removeChild(b))};m.prototype.removeChild=function(a){if(1>arguments.length)throw Error("hijos.Node.prototype.removeChild: not enough arguments.");for(var b=this.childNodes,c=0,e=b.length;c<e;c++)if(b[c]===a){if(e=b[c-1])e.nextSibling=a.nextSibling;if(e=b[c+1])e.previousSibling=a.previousSibling;a.parentNode=null;a.previousSibling=null;a.nextSibling=null;b.splice(c,1);this.firstChild=b[0]||null;this.lastChild=b[b.length-1]||null;return}throw Error("hijos.Node.prototype.removeChild: node not found.");
};m.call(m.prototype);m.mixin=function(a){for(var b in m.prototype)Object.prototype.hasOwnProperty.call(m.prototype,b)&&"function"===typeof m.prototype[b]&&(a[b]=m.prototype[b]);m.call(a)};var w={};(function(){function a(b){return b.firstChild.firstChild.firstChild}function b(a,b,d){return function(c,e){var f=e.createElement("div"),g=e.createDocumentFragment();f.innerHTML=a+c+b;for(var f=d(f),l;f;)l=f.nextSibling,g.appendChild(f),f=l;return g}}var c=/^\s+/,e=/\s+$/,g=b("","",function(a){return a.firstChild}),
f={td:b("<table><tbody><tr>","</tr></tbody></table>",function(a){return a.firstChild.firstChild.firstChild.firstChild}),tr:b("<table><tbody>","</tbody></table>",a),tbody:b("<table>","</table>",function(a){return a.firstChild.firstChild}),col:b("<table><colgroup>","</colgroup></table>",a),option:b("<select><option>a</option>","</select>",function(a){return a.firstChild.firstChild.nextSibling})};f.th=f.td;f.thead=f.tbody;f.tfoot=f.tbody;f.caption=f.tbody;f.colgroup=f.tbody;var l=/^<([a-z]+)/i;w.parseHTML=
function(a,b){a=a.replace(c,"").replace(e,"");var d=g,n=a.match(l);n&&(n=n[1].toLowerCase(),Object.prototype.hasOwnProperty.call(f,n)&&(d=f[n]));return d(a,b||document)}})();var s={};(function(){function a(b,d){return"function"===typeof b[d]||"object"===typeof b[d]&&null!==b[d]}function b(b,c){return c.id===b?c:a(c,"getElementById")?c.getElementById(b):a(c,"querySelector")?c.querySelector("#"+b):g(c,function(a){return a.id===b})}function c(a,b){a=a?a.toUpperCase():"*";if(b)var d=RegExp("(?:^|\\s+)"+
b+"(?:\\s+|$)");return function(c){return("*"===a||c.tagName&&c.tagName.toUpperCase()===a)&&(!b||d.test(c.className))}}function e(a,b){function d(a){b(a)&&c.push(a);for(a=a.firstChild;a;)d(a),a=a.nextSibling}var c=[];d(a);return c}function g(a,b){function d(a){if(b(a))return a;for(a=a.firstChild;a;){var c=d(a);if(c)return c;a=a.nextSibling}}return d(a)}var f=/^\s+/,l=/\s+$/,h=/^#(\S+)$/,m=/^([\w-]+)?(?:\.([\w-]+))?$/;s.findAll=function(g,n){g=g.replace(f,"").replace(l,"");n=n||document;var r;if(r=
g.match(h))return(r=b(r[1],n))?[r]:[];if(r=g.match(m)){var k=c(r[1],r[2]);if(a(n,"querySelectorAll")){r=[];k(n)&&r.push(n);for(var k=n.querySelectorAll(g),q=0,s=k.length;q<s;q++)r.push(k[q]);return r}return e(n,k)}throw Error('grail.findAll: Unsupported selector "'+g+'".');};s.find=function(e,n){e=e.replace(f,"").replace(l,"");n=n||document;var k;if(k=e.match(h))return b(k[1],n);if(k=e.match(m))return k=c(k[1],k[2]),a(n,"querySelector")?k(n)?n:n.querySelector(e):g(n,k);throw Error('grail.find: Unsupported selector "'+
e+'".');}})();var h;(function(){var a=0;h=function(){this._hormigas_ObjectSet_elements={};for(var a=this.size=0,d=arguments.length;a<d;a++)this.add(arguments[a])};h.superConstructor=Object;h.prototype.has=function(a){return Object.prototype.hasOwnProperty.call(a,"_hormigas_ObjectSet_id")&&Object.prototype.hasOwnProperty.call(this._hormigas_ObjectSet_elements,a._hormigas_ObjectSet_id)};h.prototype.add=function(b){if(this.has(b))return!1;Object.prototype.hasOwnProperty.call(b,"_hormigas_ObjectSet_id")||
(b._hormigas_ObjectSet_id=a++);this._hormigas_ObjectSet_elements[b._hormigas_ObjectSet_id]=b;this.size++;return!0};h.prototype["delete"]=function(a){return this.has(a)?(delete this._hormigas_ObjectSet_elements[a._hormigas_ObjectSet_id],this.size--,!0):!1};h.prototype.clear=function(){return 0<this.size?(this._hormigas_ObjectSet_elements={},this.size=0,!0):!1};h.prototype.toArray=function(){var a=[],d;for(d in this._hormigas_ObjectSet_elements)Object.prototype.hasOwnProperty.call(this._hormigas_ObjectSet_elements,
d)&&a.push(this._hormigas_ObjectSet_elements[d]);return a};h.prototype.forEach=function(a,d){for(var e in this._hormigas_ObjectSet_elements)Object.prototype.hasOwnProperty.call(this._hormigas_ObjectSet_elements,e)&&a.call(d,this._hormigas_ObjectSet_elements[e])};h.prototype.every=function(a,d){for(var e in this._hormigas_ObjectSet_elements)if(Object.prototype.hasOwnProperty.call(this._hormigas_ObjectSet_elements,e)&&!a.call(d,this._hormigas_ObjectSet_elements[e]))return!1;return!0};h.prototype.some=
function(a,d){for(var e in this._hormigas_ObjectSet_elements)if(Object.prototype.hasOwnProperty.call(this._hormigas_ObjectSet_elements,e)&&a.call(d,this._hormigas_ObjectSet_elements[e]))return!0;return!1};h.prototype.reduce=function(a){var d=this.toArray(),e=0,g=d.length,f;if(1<arguments.length)f=arguments[1];else{if(1>g)throw new TypeError("reduce of empty set with no initial value");e=1;f=d[0]}for(;e<g;)f=a.call(void 0,f,d[e]),e++;return f}})();h.call(h.prototype);h.mixin=function(a){for(var b in h.prototype)Object.prototype.hasOwnProperty.call(h.prototype,
b)&&"function"===typeof h.prototype[b]&&(a[b]=h.prototype[b]);h.call(a)};var a={};a.create=function(){function a(){}return function(b){a.prototype=b;b=new a;a.prototype=null;return b}}();a.borrow=function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};a.subclass=function(d,b,c){c=c||{};var e=c.properties,g=this;d=d[b]=Object.prototype.hasOwnProperty.call(c,"constructor")?c.constructor:function(){g.apply(this,arguments)};d.superConstructor=g;b=d.prototype=a.create(g.prototype);
b.constructor=d;e&&a.borrow(b,e);d.subclass=function(){g.subclass.apply(this,arguments)}};a.on=t;a.off=u;a.purge=v;a.Leaf=q;a.Node=m;a.Model=function(){k.call(this)};a.Model.superConstructor=k;a.Model.prototype=a.create(k.prototype);a.Model.prototype.constructor=a.Model;a.Model.prototype.destroy=function(){this.dispatchEvent({type:"destroy"})};a.SetModel=function(){h.apply(this,arguments);a.Model.call(this)};a.SetModel.superConstructor=a.Model;a.SetModel.prototype=a.create(a.Model.prototype);a.SetModel.prototype.constructor=
a.SetModel;h.mixin(a.SetModel.prototype);a.SetModel.prototype.add=function(){for(var a=[],b=0,c=arguments.length;b<c;b++){var e=arguments[b];h.prototype.add.call(this,e)&&(a.push(e),"function"===typeof e.addEventListener&&"function"===typeof e.removeEventListener&&e.addEventListener("destroy",this),"function"===typeof e.addParentEventTarget&&"function"===typeof e.removeParentEventTarget&&e.addParentEventTarget(this))}(b=0<a.length)&&this.dispatchEvent({type:"change",addedTargets:a,deletedTargets:[]});
return b};a.SetModel.prototype["delete"]=function(){for(var a=[],b=0,c=arguments.length;b<c;b++){var e=arguments[b];h.prototype["delete"].call(this,e)&&(a.push(e),"function"===typeof e.removeEventListener&&e.removeEventListener("destroy",this),"function"===typeof e.removeParentEventTarget&&e.removeParentEventTarget(this))}(b=0<a.length)&&this.dispatchEvent({type:"change",addedTargets:[],deletedTargets:a});return b};a.SetModel.prototype.clear=function(){var a=this.toArray(),b=h.prototype.clear.call(this);
if(b){for(var c=0,e=a.length;c<e;c++){var g=a[c];"function"===typeof g.removeEventListener&&g.removeEventListener("destroy",this);"function"===typeof g.removeParentEventTarget&&g.removeParentEventTarget(this)}this.dispatchEvent({type:"change",addedTargets:[],deletedTargets:a})}return b};a.SetModel.prototype.handleEvent=function(a){if("destroy"===a.type&&a.currentTarget===a.target)this["delete"](a.target)};a.View=function(d,b){a.Node.call(this);this.setModel(d);this.setController(b)};a.View.superConstructor=
a.Node;a.View.prototype=a.create(a.Node.prototype);a.View.prototype.constructor=a.View;a.View.prototype.destroy=function(){a.purge(this);this._model=null;this._controller&&(this._controller.destroy(),this._controller=null);a.Node.prototype.destroy.call(this)};a.View.prototype.update=function(){};a.View.prototype.getModel=function(){return this._model};a.View.prototype.setModel=function(a){this._setModelAndController(a,this._controller)};a.View.prototype.getDefaultControllerConstructor=function(){return a.Controller};
a.View.prototype.getDefaultController=function(){return new (this.getDefaultControllerConstructor())};a.View.prototype.getController=function(){this._controller||this.setController(this.getDefaultController());return this._controller};a.View.prototype.setController=function(a){this._setModelAndController(this._model,a)};a.View.prototype.getModelActions=function(){return{change:"update"}};a.View.prototype._setModelAndController=function(d,b){var c,e;if(this._model!==d){if(this._model){e=this._lastModelActions;
for(c in e)Object.prototype.hasOwnProperty.call(e,c)&&a.off(this._model,c,this,e[c]);delete this._lastModelActions}if(d)for(c in e=this._lastModelActions=this.getModelActions()||{},e)if(Object.prototype.hasOwnProperty.call(e,c))a.on(d,c,this,e[c]);this._model=d}this._controller!==b&&this._controller&&(this._controller.setView(null),this._controller.setModel(null));b&&(b.setView(this),b.setModel(d));this._controller=b};a.ElementView=function(d,b,c){a.View.call(this,d,b);this.setDocument(c)};a.ElementView.superConstructor=
a.View;a.ElementView.prototype=a.create(a.View.prototype);a.ElementView.prototype.constructor=a.ElementView;a.ElementView.prototype.getDocument=function(){return this._doc||document};a.ElementView.prototype.setDocument=function(a){this._doc=a;for(var b=this.childNodes,c=0,e=b.length;c<e;c++)b[c].setDocument(a)};a.ElementView.prototype.getTemplate=function(){return"<div></div>"};a.ElementView.prototype.getUIActions=function(){return{}};a.ElementView.prototype.build=function(){this._rootEl||(this.buildTemplate(),
this.buildUIActions(),this.buildData(),this.buildChildViews());return this._rootEl};a.ElementView.prototype.buildTemplate=function(){this._rootEl=w.parseHTML(this.getTemplate(),this.getDocument()).firstChild};(function(){var d=/^(\S+)\s*(.*)$/;a.ElementView.prototype.buildUIActions=function(){var b=this.getUIActions(),c;for(c in b)if(Object.prototype.hasOwnProperty.call(b,c))for(var e=c.match(d),g=e[1],f=b[c],e=this.findAll(e[2],this._rootEl),l=0,h=e.length;l<h;l++)a.on(e[l],g,this,f)}})();a.ElementView.prototype.buildData=
function(){};a.ElementView.prototype.buildChildViews=function(){for(var a=this.childNodes,b=0,c=a.length;b<c;b++)this.getContainerEl().appendChild(a[b].build())};a.ElementView.prototype.getContainerEl=function(){return this.build()};a.ElementView.prototype.insertBefore=function(d,b){a.View.prototype.insertBefore.call(this,d,b);this._rootEl&&this.getContainerEl().insertBefore(d.build(),b?b.build():null)};a.ElementView.prototype.removeChild=function(d){a.View.prototype.removeChild.call(this,d);this._rootEl&&
this.getContainerEl().removeChild(d.build())};a.ElementView.prototype.find=function(a){return s.find(a,this.build())};a.ElementView.prototype.findAll=function(a){return s.findAll(a,this.build())};a.SetView=function(){a.ElementView.apply(this,arguments)};a.SetView.superConstructor=a.ElementView;a.SetView.prototype=a.create(a.ElementView.prototype);a.SetView.prototype.constructor=a.SetView;a.SetView.prototype.buildChildViews=function(){for(var a=this.getModel().toArray(),b=0,c=a.length;b<c;b++)this.appendChild(this.createChildView(a[b]))};
a.SetView.prototype.createChildView=function(d){return new a.ElementView(d)};a.SetView.prototype.update=function(a){a.target===this.getModel()&&(a.addedTargets&&a.addedTargets.length&&this.handleAdd(a),a.deletedTargets&&a.deletedTargets.length&&this.handleDelete(a))};a.SetView.prototype.handleAdd=function(a){a=a.addedTargets;for(var b=0,c=a.length;b<c;b++)this.appendChild(this.createChildView(a[b]))};a.SetView.prototype.handleDelete=function(a){a=a.deletedTargets;for(var b=0,c=a.length;b<c;b++)for(var e=
a[b],g=this.childNodes,f=0,l=g.length;f<l;f++){var h=g[f];if(h.getModel()===e){this.removeChild(h);h.destroy();break}}};a.Controller=function(){};a.Controller.superConstructor=Object;a.Controller.prototype.destroy=function(){this._model=null;this._view&&(this._view.setController(null),this._view=null)};a.Controller.prototype.getModel=function(){return this._model};a.Controller.prototype.setModel=function(a){this._model=a};a.Controller.prototype.getView=function(){return this._view};a.Controller.prototype.setView=
function(a){this._view=a};a.Model.subclass=function(){a.subclass.apply(this,arguments)};a.SetModel.subclass=function(){a.Model.subclass.apply(this,arguments)};a.View.subclass=function(d,b,c){c=c||{};var e=c.controllerConstructor,g=c.controllerConstructorName||b.replace(/(View|)$/,"Controller"),f=c.modelActions,h=c.properties||(c.properties={});Object.prototype.hasOwnProperty.call(h,"getDefaultControllerConstructor")||(h.getDefaultControllerConstructor=function(){return e||d[g]});f&&!Object.prototype.hasOwnProperty.call(h,
"getModelActions")&&(h.getModelActions=function(){return f});a.subclass.call(this,d,b,c)};a.ElementView.subclass=function(d,b,c){c=c||{};var e=c.template,g=c.templateName||b.replace(/(View|)$/,"Template"),f=c.uiActions,h=c.properties||(c.properties={});Object.prototype.hasOwnProperty.call(h,"getTemplate")||(e?h.getTemplate=function(){return e}:g&&(h.getTemplate=function(){return d[g]}));if(f){Object.prototype.hasOwnProperty.call(h,"getUIActions")||(h.getUIActions=function(){return f});for(var k in f)if(Object.prototype.hasOwnProperty.call(f,
k)){var m=f[k];Object.prototype.hasOwnProperty.call(h,m)||m in this.prototype||function(a){h[a]=function(b){this.getController()[a](b)}}(m)}}a.View.subclass.call(this,d,b,c)};a.SetView.subclass=function(){a.ElementView.subclass.apply(this,arguments)};a.Controller.subclass=function(){a.subclass.apply(this,arguments)};return a}();
/*
//@ sourceMappingURL=maria-min.map
*/

