import '../specs/compiler.spec.js'
import '../specs/components-registration.spec.js'
import '../specs/components-rendering.spec.js'
import '../specs/lifecycle-events.spec.js'
import '../specs/plugins-api.spec.js'
import '../specs/public-api.spec.js'
import '../specs/slots.spec.js'
import '../specs/state-and-props.spec.js'
